"""add_log_levels

Revision ID: 6b8b29a4accd
Revises: 8e760264c79a
Create Date: 2026-04-14 21:36:09.948740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8b29a4accd'
down_revision: Union[str, None] = '8e760264c79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('level', sa.String(length=10), nullable=False))
    op.add_column('system_logs', sa.Column('level', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_logs', 'level')
    op.drop_column('audit_logs', 'level')
    # ### end Alembic commands ###
