"""initial_schema

Revision ID: 8e760264c79a
Revises: 
Create Date: 2026-04-14 21:25:42.853089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e760264c79a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher', 'student', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('force_password_reset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("email REGEXP '^[0-9]{2}[a-zA-Z]{3}[0-9]{3}@[a-zA-Z]+\\.clg\\.ac\\.in$' OR email REGEXP '^[a-zA-Z]+\\.[a-zA-Z]+@clg\\.ac\\.in$' OR email = 'admin@clg.ac.in'", name='valid_user_emails'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('active_sessions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('access_token_jti', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_jti'),
    sa.UniqueConstraint('refresh_token_jti'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('school_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('forum_threads',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('email_attempted', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('action', sa.Enum('login_success', 'login_failed', 'logout', 'exam_attempt_start', name='iplogaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('exam_created', 'exam_published', 'results_published', 'users_created', 'course_created', 'course_activated', 'course_deactivated', name='systemlogeventtype'), nullable=False),
    sa.Column('actor_id', sa.BIGINT(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.BIGINT(), nullable=False),
    sa.Column('year', sa.CHAR(length=2), nullable=False),
    sa.Column('mode', sa.Enum('T', 'P', name='coursemode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('discussion_posts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('restrict_school_id', sa.BIGINT(), nullable=True),
    sa.Column('restrict_branch_id', sa.BIGINT(), nullable=True),
    sa.Column('restrict_batch_year', sa.CHAR(length=2), nullable=True),
    sa.Column('restrict_emails', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restrict_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['restrict_school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_posts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.BIGINT(), nullable=False),
    sa.Column('parent_post_id', sa.BIGINT(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_post_id'], ['forum_posts.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('batch_year', sa.CHAR(length=2), nullable=False),
    sa.Column('branch_id', sa.BIGINT(), nullable=False),
    sa.Column('roll_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('course_assignments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=False),
    sa.Column('teacher_id', sa.BIGINT(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_enrollments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=False),
    sa.Column('student_id', sa.BIGINT(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('enrolled_by', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussion_replies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['discussion_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('negative_marking_factor', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('total_marks', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('passing_marks', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('results_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('results_published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_attempts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BIGINT(), nullable=False),
    sa.Column('student_id', sa.BIGINT(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'auto_submitted', name='attemptstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BIGINT(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'subjective', name='questiontype'), nullable=False),
    sa.Column('marks', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_results',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BIGINT(), nullable=False),
    sa.Column('exam_id', sa.BIGINT(), nullable=False),
    sa.Column('student_id', sa.BIGINT(), nullable=False),
    sa.Column('mcq_marks_awarded', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('subjective_marks_awarded', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('negative_marks_deducted', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('total_marks_awarded', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.Column('published_by', sa.BIGINT(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_table('mcq_options',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.Column('option_label', sa.CHAR(length=1), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctor_snapshots',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BIGINT(), nullable=False),
    sa.Column('gcs_path', sa.String(length=500), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctor_violations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BIGINT(), nullable=False),
    sa.Column('violation_type', sa.Enum('tab_switch', 'fullscreen_exit', 'camera_unavailable', 'copy_paste_attempt', name='violationtype'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.Column('selected_option_id', sa.BIGINT(), nullable=True),
    sa.Column('subjective_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_awarded', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['mcq_options.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjective_grades',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.BIGINT(), nullable=False),
    sa.Column('graded_by', sa.BIGINT(), nullable=False),
    sa.Column('marks_awarded', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjective_grades')
    op.drop_table('answers')
    op.drop_table('proctor_violations')
    op.drop_table('proctor_snapshots')
    op.drop_table('mcq_options')
    op.drop_table('exam_results')
    op.drop_table('questions')
    op.drop_table('exam_attempts')
    op.drop_table('exams')
    op.drop_table('discussion_replies')
    op.drop_table('course_enrollments')
    op.drop_table('course_assignments')
    op.drop_table('student_profiles')
    op.drop_table('forum_posts')
    op.drop_table('discussion_posts')
    op.drop_table('courses')
    op.drop_table('system_logs')
    op.drop_table('password_reset_tokens')
    op.drop_table('notifications')
    op.drop_table('ip_logs')
    op.drop_table('forum_threads')
    op.drop_table('branches')
    op.drop_table('audit_logs')
    op.drop_table('active_sessions')
    op.drop_table('users')
    op.drop_table('schools')
    # ### end Alembic commands ###
